(define (get-num n)
  (+ n 10)
  )

(define (make-monitored f)
  (define counter 0)
  (define (mf m)
    (cond ((eq? m 'how-many-calls?)
	   counter)
	  ((eq? m 'reset-count)
	   (begin (set! counter 0)
		(counter)))
	  (else (begin ((f m))
		       (set! counter (+ 1 counter))))
	  )
    )
  mf)
